// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  container: string;
  extra: string;
  extraActive: string;
  extraImage: string;
  layout: string;
  resource: string;
}
declare const cssExports: CssExports;
export default cssExports;
