// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  container: string;
  video: string;
}
declare const cssExports: CssExports;
export default cssExports;
