// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  container: string;
  contentSelector: string;
  contentTitle: string;
  popoverBtn: string;
  popoverOpen: string;
}
declare const cssExports: CssExports;
export default cssExports;
