// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  block: string;
  container: string;
  label: string;
  text: string;
  value: string;
}
declare const cssExports: CssExports;
export default cssExports;
