// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  fullscreenBg: string;
  fullscreenContent: string;
  fullscreenModal: string;
  fullscreenWrap: string;
}
declare const cssExports: CssExports;
export default cssExports;
