// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  checkbox: string;
  container: string;
  operator: string;
  selected: string;
}
declare const cssExports: CssExports;
export default cssExports;
