"""VNCCS Nodes - ComfyUI nodes for visual novel character creation."""


try:
    from .character_creator import NODE_CLASS_MAPPINGS as CHARACTER_CREATOR_MAPPINGS
    from .character_selector import NODE_CLASS_MAPPINGS as CHARACTER_SELECTOR_MAPPINGS
    from .dataset_generator import NODE_CLASS_MAPPINGS as DATASET_GENERATOR_MAPPINGS
    from .emotion_generator import NODE_CLASS_MAPPINGS as EMOTION_GENERATOR_MAPPINGS
    from .emotion_generator_v2 import NODE_CLASS_MAPPINGS as EMOTION_GENERATOR_V2_MAPPINGS
    from .sheet_crop import NODE_CLASS_MAPPINGS as SHEET_CROP_MAPPINGS
    from .sheet_manager import NODE_CLASS_MAPPINGS as SHEET_MANAGER_MAPPINGS
    from .sprite_generator import NODE_CLASS_MAPPINGS as SPRITE_GENERATOR_MAPPINGS
    from .vnccs_pipe import NODE_CLASS_MAPPINGS as VNCCS_PIPE_MAPPINGS
    from .vnccs_qwen_encoder import NODE_CLASS_MAPPINGS as VNCCS_QWEN_ENCODER_MAPPINGS
    from .sampler_scheduler_picker import NODE_CLASS_MAPPINGS as SAMPLER_SCHEDULER_PICKER_MAPPINGS
    from .common_nodes import NODE_CLASS_MAPPINGS as COMMON_NODES_MAPPINGS
    from .pose_generator import NODE_CLASS_MAPPINGS as POSE_GENERATOR_CLASS_MAPPINGS
    from .vnccs_utils import NODE_CLASS_MAPPINGS as VNCCS_UTILS_MAPPINGS
    from .vnccs_chroma_key_experimental import NODE_CLASS_MAPPINGS as VNCCS_CHROMA_KEY_EXPERIMENTAL_MAPPINGS
    from .vnccs_api import NODE_CLASS_MAPPINGS as VNCCS_API_MAPPINGS
    from .vnccs_control_center import NODE_CLASS_MAPPINGS as VNCCS_CONTROL_CENTER_MAPPINGS
    from .character_generator import NODE_CLASS_MAPPINGS as CHARACTER_GENERATOR_MAPPINGS
    from .service_nodes import NODE_CLASS_MAPPINGS as SERVICE_NODES_MAPPINGS
    from .character_creator_v2 import NODE_CLASS_MAPPINGS as CHARACTER_CREATOR_V2_MAPPINGS
    from .character_cloner import NODE_CLASS_MAPPINGS as CHARACTER_CLONER_MAPPINGS
    from .clothes_designer import NODE_CLASS_MAPPINGS as CLOTHES_DESIGNER_MAPPINGS
    from .migration_assistant import NODE_CLASS_MAPPINGS as MIGRATION_ASSISTANT_MAPPINGS
    from .sprite_manager import NODE_CLASS_MAPPINGS as SPRITE_MANAGER_MAPPINGS


    from .character_creator import NODE_DISPLAY_NAME_MAPPINGS as CHARACTER_CREATOR_DISPLAY_MAPPINGS
    from .character_selector import NODE_DISPLAY_NAME_MAPPINGS as CHARACTER_SELECTOR_DISPLAY_MAPPINGS
    from .dataset_generator import NODE_DISPLAY_NAME_MAPPINGS as DATASET_GENERATOR_DISPLAY_MAPPINGS
    from .emotion_generator import NODE_DISPLAY_NAME_MAPPINGS as EMOTION_GENERATOR_DISPLAY_MAPPINGS
    from .emotion_generator_v2 import NODE_DISPLAY_NAME_MAPPINGS as EMOTION_GENERATOR_V2_DISPLAY_MAPPINGS
    from .sheet_crop import NODE_DISPLAY_NAME_MAPPINGS as SHEET_CROP_DISPLAY_MAPPINGS
    from .sheet_manager import NODE_DISPLAY_NAME_MAPPINGS as SHEET_MANAGER_DISPLAY_MAPPINGS
    from .sprite_generator import NODE_DISPLAY_NAME_MAPPINGS as SPRITE_GENERATOR_DISPLAY_MAPPINGS
    from .vnccs_pipe import NODE_DISPLAY_NAME_MAPPINGS as VNCCS_PIPE_DISPLAY_MAPPINGS
    from .vnccs_qwen_encoder import NODE_DISPLAY_NAME_MAPPINGS as VNCCS_QWEN_ENCODER_DISPLAY_MAPPINGS
    from .sampler_scheduler_picker import NODE_DISPLAY_NAME_MAPPINGS as SAMPLER_SCHEDULER_PICKER_DISPLAY_MAPPINGS
    from .common_nodes import NODE_DISPLAY_NAME_MAPPINGS as COMMON_NODES_DISPLAY_MAPPINGS
    from .pose_generator import NODE_DISPLAY_NAME_MAPPINGS as POSE_GENERATOR_DISPLAY_MAPPINGS
    from .vnccs_utils import NODE_DISPLAY_NAME_MAPPINGS as VNCCS_UTILS_DISPLAY_MAPPINGS
    from .vnccs_chroma_key_experimental import NODE_DISPLAY_NAME_MAPPINGS as VNCCS_CHROMA_KEY_EXPERIMENTAL_DISPLAY_MAPPINGS
    from .vnccs_api import NODE_DISPLAY_NAME_MAPPINGS as VNCCS_API_DISPLAY_MAPPINGS
    from .vnccs_control_center import NODE_DISPLAY_NAME_MAPPINGS as VNCCS_CONTROL_CENTER_DISPLAY_MAPPINGS
    from .character_generator import NODE_DISPLAY_NAME_MAPPINGS as CHARACTER_GENERATOR_DISPLAY_MAPPINGS
    from .service_nodes import NODE_DISPLAY_NAME_MAPPINGS as SERVICE_NODES_DISPLAY_MAPPINGS
    from .character_creator_v2 import NODE_DISPLAY_NAME_MAPPINGS as CHARACTER_CREATOR_V2_DISPLAY_MAPPINGS
    from .character_cloner import NODE_DISPLAY_NAME_MAPPINGS as CHARACTER_CLONER_DISPLAY_MAPPINGS
    from .clothes_designer import NODE_DISPLAY_NAME_MAPPINGS as CLOTHES_DESIGNER_DISPLAY_MAPPINGS
    from .migration_assistant import NODE_DISPLAY_NAME_MAPPINGS as MIGRATION_ASSISTANT_DISPLAY_MAPPINGS
    from .sprite_manager import NODE_DISPLAY_NAME_MAPPINGS as SPRITE_MANAGER_DISPLAY_MAPPINGS


    NODE_CLASS_MAPPINGS = {
        **CHARACTER_CREATOR_MAPPINGS,
        **CHARACTER_SELECTOR_MAPPINGS,
        **DATASET_GENERATOR_MAPPINGS,
        **EMOTION_GENERATOR_MAPPINGS,
        **EMOTION_GENERATOR_V2_MAPPINGS,
        **SHEET_CROP_MAPPINGS,
        **SHEET_MANAGER_MAPPINGS,
        **SPRITE_GENERATOR_MAPPINGS,
        **VNCCS_PIPE_MAPPINGS,
        **VNCCS_QWEN_ENCODER_MAPPINGS,
        **SAMPLER_SCHEDULER_PICKER_MAPPINGS,
        **COMMON_NODES_MAPPINGS,
        **POSE_GENERATOR_CLASS_MAPPINGS,
        **VNCCS_UTILS_MAPPINGS,
        **VNCCS_CHROMA_KEY_EXPERIMENTAL_MAPPINGS,
        **VNCCS_API_MAPPINGS,
        **VNCCS_CONTROL_CENTER_MAPPINGS,
        **CHARACTER_GENERATOR_MAPPINGS,
        **SERVICE_NODES_MAPPINGS,
        **CHARACTER_CREATOR_V2_MAPPINGS,
        **CHARACTER_CLONER_MAPPINGS,
        **CLOTHES_DESIGNER_MAPPINGS,
        **MIGRATION_ASSISTANT_MAPPINGS,
        **SPRITE_MANAGER_MAPPINGS,
    }

    NODE_DISPLAY_NAME_MAPPINGS = {
        **CHARACTER_CREATOR_DISPLAY_MAPPINGS,
        **CHARACTER_SELECTOR_DISPLAY_MAPPINGS,
        **DATASET_GENERATOR_DISPLAY_MAPPINGS,
        **EMOTION_GENERATOR_DISPLAY_MAPPINGS,
        **EMOTION_GENERATOR_V2_DISPLAY_MAPPINGS,
        **SHEET_CROP_DISPLAY_MAPPINGS,
        **SHEET_MANAGER_DISPLAY_MAPPINGS,
        **SPRITE_GENERATOR_DISPLAY_MAPPINGS,
        **VNCCS_PIPE_DISPLAY_MAPPINGS,
        **VNCCS_QWEN_ENCODER_DISPLAY_MAPPINGS,
        **SAMPLER_SCHEDULER_PICKER_DISPLAY_MAPPINGS,
        **COMMON_NODES_DISPLAY_MAPPINGS,
        **POSE_GENERATOR_DISPLAY_MAPPINGS,
        **VNCCS_UTILS_DISPLAY_MAPPINGS,
        **VNCCS_CHROMA_KEY_EXPERIMENTAL_DISPLAY_MAPPINGS,
        **VNCCS_API_DISPLAY_MAPPINGS,
        **VNCCS_CONTROL_CENTER_DISPLAY_MAPPINGS,
        **CHARACTER_GENERATOR_DISPLAY_MAPPINGS,
        **SERVICE_NODES_DISPLAY_MAPPINGS,
        **CHARACTER_CREATOR_V2_DISPLAY_MAPPINGS,
        **CHARACTER_CLONER_DISPLAY_MAPPINGS,
        **CLOTHES_DESIGNER_DISPLAY_MAPPINGS,
        **MIGRATION_ASSISTANT_DISPLAY_MAPPINGS,
        **SPRITE_MANAGER_DISPLAY_MAPPINGS,
    }
except Exception as e:
    import traceback
    print(f"❌ [VNCCS] CRITICAL REGISTRATION ERROR in nodes/__init__.py: {e}")
    traceback.print_exc()
    NODE_CLASS_MAPPINGS = {}
    NODE_DISPLAY_NAME_MAPPINGS = {}


__all__ = ['NODE_CLASS_MAPPINGS', 'NODE_DISPLAY_NAME_MAPPINGS']
