// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  arcoTagIcon: string;
  tag: string;
}
declare const cssExports: CssExports;
export default cssExports;
