workspace:
  launch:
    button:
      name: ComfyUI Cloud起飞🚀
      description:  ComfyUI Cloud 💪 YYDS
      hoverImage: .cnb/click.gif
    disabled: false
    autoOpenWebIDE: true
    hoverImage: .cnb/click.gif