// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  carousel: string;
  container: string;
  hiddenCarousel: string;
  image: string;
  loading: string;
  responsiveBox: string;
  tag: string;
}
declare const cssExports: CssExports;
export default cssExports;
