// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  container: string;
  emptyImg: string;
  emptyText: string;
  loading: string;
  loadingText: string;
}
declare const cssExports: CssExports;
export default cssExports;
