// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  container: string;
  hidden: string;
  image: string;
  loading: string;
  loadingAnimation: string;
}
declare const cssExports: CssExports;
export default cssExports;
