// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  accordionContent: string;
  accordionContentExpanded: string;
  actions: string;
  button: string;
  clickableText: string;
  contentContainer: string;
  countText: string;
  footer: string;
  hightLightText: string;
  icon: string;
  popoverContainer: string;
  resetText: string;
  rotate180Animation: string;
  rotateAnimation: string;
  search: string;
  selectItemCheckbox: string;
  selectItemColumn: string;
  selectItemContainer: string;
  selectItemRow: string;
  text: string;
  triggerContainer: string;
}
declare const cssExports: CssExports;
export default cssExports;
