// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  container: string;
  icon: string;
  img: string;
  imgContainer: string;
  left: string;
  right: string;
}
declare const cssExports: CssExports;
export default cssExports;
