// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  card: string;
  cardCount: string;
  cardText: string;
  container: string;
  content: string;
  finalCount: string;
  finalCountDefault: string;
  header: string;
  headerCount: string;
  headerTitle: string;
  section: string;
  titleName: string;
}
declare const cssExports: CssExports;
export default cssExports;
