from .ipadapter_flux import NODE_CLASS_MAPPINGS as BASIC_NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as BASIC_NODE_DISPLAY_NAME_MAPPINGS
from .ipadapter_flux_advanced import NODE_CLASS_MAPPINGS as ADVANCED_NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as ADVANCED_NODE_DISPLAY_NAME_MAPPINGS

# Merge the mappings
NODE_CLASS_MAPPINGS = {
    **BASIC_NODE_CLASS_MAPPINGS, 
    **ADVANCED_NODE_CLASS_MAPPINGS
}
NODE_DISPLAY_NAME_MAPPINGS = {
    **BASIC_NODE_DISPLAY_NAME_MAPPINGS, 
    **ADVANCED_NODE_DISPLAY_NAME_MAPPINGS
}

__all__ = ['NODE_CLASS_MAPPINGS', 'NODE_DISPLAY_NAME_MAPPINGS']
