// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  formItemLayout: string;
  formItemLayoutLabel: string;
}
declare const cssExports: CssExports;
export default cssExports;
