// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  container: string;
  header: string;
  headerLeft: string;
  headerText: string;
  headerTitle: string;
}
declare const cssExports: CssExports;
export default cssExports;
