// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  checkbox: string;
  dragIcon: string;
  listContainer: string;
  popoverContainer: string;
  renderAudio: string;
  renderImage: string;
  renderText: string;
  renderVideo: string;
  sortableItem: string;
}
declare const cssExports: CssExports;
export default cssExports;
